### ISSUE TITLE
Connection refused when try watch the video

### ISSUE THREAD

**Issue by MattTrovao** [sricharankrishnan/click-image-play-youtube-video#11]
Hey, I need a little help:

I am making a website in Wordpress, and using your plugin, but when I click to watch the video I have the message: **The connection to www.youtube.com was refused.** .

Before I make the theme, I create everything in HTML and CSS, that way I can work faster, and when was just this way I could open the videos, but now it Wordpress I can't. Do you have any ideia of why this happend?

I am making the website in localhost, but used to work fine until I put the Wordpress. I have one online version, but just with the HTML and CSS.

Wordpress Version: 5.3.2
jQuery Version: 3.4.1

**Comment by sricharankrishnan** [comment]
Hey Matt,
Good day. Could you show me the error code that you're getting with the browser console please? Screen shot

**Comment by sricharankrishnan** [comment]
Hey Matt,
Here are some points for you:
1. Ran the code in localhost and no issues were found so far.
2. I also searched on google to see if this was some issue that other people have faced and apparently there are some articles where people go into some issues with youtube on WP
3. May be you need to do some setting changes in your WP website
4. https://wordpress.org/support/topic/youtube-refused-to-connect/ and https://illuminea.com/why-cant-i-embed-youtube-videos-in-wordpress/ may help?
5. Otherwise if you would like me to build something that is specific for Wordpress, let me know and I'll do my best

Let me know your thoughts on the above

**Comment by MattTrovao** [comment]
Hey, the error I have in console is:
`Refused to display 'https://www.youtube.com/watch?v=UeZtlFeEcNg' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`
The first link wasn't very helpfull but the second is helping me, I search a little and some people say the link is wrong, the corret one should be `https://www.youtube.com/embed/UeZtlFeEcNg`, I try with that link and it works.

Thanks for your help, I will close this issue.

Also, I will probably use a lot your plugin, so thanks for the awesome plguin.

**Comment by sricharankrishnan** [comment]
Hey Matt,
Most welcome and I am happy that's things worked out. I'd be really grateful if you could support my plugin with a star! Have a nice day
